version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: identity-service
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: identity-service
      MYSQL_USER: root_user
      MYSQL_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: